"""empty message

Revision ID: ec4d4fce3eeb
Revises: 7e3d4427b0e8
Create Date: 2020-11-25 11:11:18.553056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4d4fce3eeb'
down_revision = '7e3d4427b0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposals', 'geocoordinates',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('proposals', 'location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proposals', 'location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('proposals', 'geocoordinates',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
