version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - static_volume:/home/app/app/static
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/app/static
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume: