"""add relation in pln_tariffs

Revision ID: 005eceebb3a9
Revises: a88fc2e48f0c
Create Date: 2021-05-27 15:42:16.862510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005eceebb3a9'
down_revision = 'a88fc2e48f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('pln_tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposals', 'pln_tariffs', ['pln_tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'pln_tariff_id')
    # ### end Alembic commands ###
