"""add proposal number field in proposal table

Revision ID: 102a5f6ccc5f
Revises: 1165321cff93
Create Date: 2021-06-23 09:04:01.230109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102a5f6ccc5f'
down_revision = '1165321cff93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('proposal_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'proposal_no')
    # ### end Alembic commands ###
