"""Add qty_prod

Revision ID: 1a275e5a500d
Revises: c270f1ce6f3a
Create Date: 2021-07-05 13:42:43.595332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a275e5a500d'
down_revision = 'c270f1ce6f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('qty_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'qty_id')
    # ### end Alembic commands ###
