"""Relation proposal_product

Revision ID: 21a77b587f36
Revises: 102a5f6ccc5f
Create Date: 2021-07-05 09:32:42.132334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a77b587f36'
down_revision = '102a5f6ccc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_proposal_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'proposal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_proposal_id_fkey', 'products', 'proposals', ['proposal_id'], ['id'])
    # ### end Alembic commands ###
