"""add bid table

Revision ID: 2a0967e1ae64
Revises: 512f38e28c30
Create Date: 2021-07-13 09:27:17.071343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0967e1ae64'
down_revision = '512f38e28c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('attachment', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('proposals', 'bid_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('bid_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('bids')
    # ### end Alembic commands ###
