"""fixing bigint 3

Revision ID: 35a9fe54167e
Revises: a24e151caef8
Create Date: 2021-11-02 10:30:23.229388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a9fe54167e'
down_revision = 'a24e151caef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofs', sa.Column('add_construction_price2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofs', 'add_construction_price2')
    # ### end Alembic commands ###
