"""add stg60

Revision ID: 372dcce273f2
Revises: b423af0632fe
Create Date: 2021-05-24 14:01:21.478909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372dcce273f2'
down_revision = 'b423af0632fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('inverter_stg60', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'inverter_stg60')
    # ### end Alembic commands ###
