"""add project name

Revision ID: 56ca4ea31125
Revises: 68bffb8d281b
Create Date: 2021-03-10 14:30:05.133602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ca4ea31125'
down_revision = '68bffb8d281b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('project_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'project_name')
    # ### end Alembic commands ###
