"""Add qty_prod 5

Revision ID: 5a733ecb7172
Revises: ddc075089a96
Create Date: 2021-07-05 14:02:37.862766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a733ecb7172'
down_revision = 'ddc075089a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_qty_product_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'qty_product_id')
    op.add_column('qty_products', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('qty_products', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qty_products', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'qty_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qty_products', type_='foreignkey')
    op.drop_constraint(None, 'qty_products', type_='foreignkey')
    op.drop_column('qty_products', 'proposal_id')
    op.drop_column('qty_products', 'product_id')
    op.add_column('products', sa.Column('qty_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_qty_product_id_fkey', 'products', 'qty_products', ['qty_product_id'], ['id'])
    # ### end Alembic commands ###
