"""add prices inverter to proposal

Revision ID: 68bffb8d281b
Revises: ec4d4fce3eeb
Create Date: 2021-01-08 13:45:01.140567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68bffb8d281b'
down_revision = 'ec4d4fce3eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('proposals', sa.Column('energy_accounting_system', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('installation_price', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('inverter_stg20', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('inverter_stg3', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('inverter_stg6', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('transport_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'transport_price')
    op.drop_column('proposals', 'inverter_stg6')
    op.drop_column('proposals', 'inverter_stg3')
    op.drop_column('proposals', 'inverter_stg20')
    op.drop_column('proposals', 'installation_price')
    op.drop_column('proposals', 'energy_accounting_system')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
