"""fixing int

Revision ID: 6a513bf90e4e
Revises: 35a9fe54167e
Create Date: 2021-11-02 13:54:08.930593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a513bf90e4e'
down_revision = '35a9fe54167e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roofs', 'add_construction_price2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roofs', sa.Column('add_construction_price2', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
