"""Add qty_prod 6

Revision ID: 6f6f79851f79
Revises: 5a733ecb7172
Create Date: 2021-07-05 14:04:02.866832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6f79851f79'
down_revision = '5a733ecb7172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proposals_qty_id_fkey', 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'qty_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('qty_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('proposals_qty_id_fkey', 'proposals', 'qty_products', ['qty_id'], ['id'])
    # ### end Alembic commands ###
