"""add proposal.inverter stg 125 & 250

Revision ID: 71964e08a055
Revises: b3da58a4a48d
Create Date: 2021-04-16 08:45:03.650401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71964e08a055'
down_revision = 'b3da58a4a48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('inverter_stg125', sa.Integer(), nullable=True))
    op.add_column('proposals', sa.Column('inverter_stg250', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'inverter_stg250')
    op.drop_column('proposals', 'inverter_stg125')
    # ### end Alembic commands ###
