"""update proposal with pln_price

Revision ID: 7358bbf0d03d
Revises: 2347c536d8a4
Create Date: 2021-04-23 08:59:36.576673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7358bbf0d03d'
down_revision = '2347c536d8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('pln_price', sa.Integer(), nullable=True))
    op.drop_constraint('proposals_product_id_fkey', 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('proposals_product_id_fkey', 'proposals', 'products', ['product_id'], ['id'])
    op.drop_column('proposals', 'pln_price')
    # ### end Alembic commands ###
