"""relation between bid and customer

Revision ID: a24e151caef8
Revises: c865017a0449
Create Date: 2021-07-22 11:32:53.464317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24e151caef8'
down_revision = 'c865017a0449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bids', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_column('bids', 'customer_id')
    # ### end Alembic commands ###
