"""Add qty_product table

Revision ID: c270f1ce6f3a
Revises: e931fa2483fb
Create Date: 2021-07-05 11:42:12.645360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c270f1ce6f3a'
down_revision = 'e931fa2483fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qty_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('qty_product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'qty_products', ['qty_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'qty_product_id')
    op.drop_table('qty_products')
    # ### end Alembic commands ###
