"""Initial migration.

Revision ID: d91523bd6904
Revises: 
Create Date: 2020-11-05 10:30:41.354144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91523bd6904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('geocoordinates', sa.String(length=80), nullable=True),
    sa.Column('sketchup_model', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.String(), nullable=True),
    sa.Column('pv_panel', sa.Integer(), nullable=True),
    sa.Column('pv_panel_qty', sa.Integer(), nullable=True),
    sa.Column('pv_mount', sa.Integer(), nullable=True),
    sa.Column('pv_cable', sa.String(length=15), nullable=True),
    sa.Column('add_construction_qty', sa.Integer(), nullable=True),
    sa.Column('add_construction_price', sa.Integer(), nullable=True),
    sa.Column('azimuth', sa.Integer(), nullable=True),
    sa.Column('angle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solaryeardatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roof_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roof_id'], ['roofs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solarmonthdatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=15), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['solaryeardatas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solarhourdatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['solarmonthdatas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solarhourdatas')
    op.drop_table('solarmonthdatas')
    op.drop_table('solaryeardatas')
    op.drop_table('roofs')
    op.drop_table('proposals')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
