"""Add qty_prod 3

Revision ID: ddc075089a96
Revises: 1a275e5a500d
Create Date: 2021-07-05 13:53:00.456531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc075089a96'
down_revision = '1a275e5a500d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'proposals', 'qty_products', ['qty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    # ### end Alembic commands ###
