"""add bid_no in proposal

Revision ID: dfc018e13dc0
Revises: 88f9bc73cdb6
Create Date: 2021-07-09 10:16:00.460722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc018e13dc0'
down_revision = '88f9bc73cdb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('bid_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'bid_no')
    # ### end Alembic commands ###
