"""add product table

Revision ID: e029fae0d9c2
Revises: 3f7d6393ba3a
Create Date: 2021-04-16 13:53:52.991878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e029fae0d9c2'
down_revision = '3f7d6393ba3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brochure', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brochure')
    # ### end Alembic commands ###
