"""add bid table relation

Revision ID: ffa8732e25ee
Revises: 2a0967e1ae64
Create Date: 2021-07-13 09:28:28.413215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa8732e25ee'
down_revision = '2a0967e1ae64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('bid_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposals', 'bids', ['bid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'bid_id')
    # ### end Alembic commands ###
